package sistemaatletas;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author nahuel
 */
public class Atletas_GUI extends javax.swing.JFrame {

    // Crea los objetos necesarios para la persistencia
    static Equipo_Nacional equipo;
    static ArrayList<Prueba> listaPruebas;
    
    /**
     * Creates new form Atletas_GUI
     */
    public Atletas_GUI() {
        initComponents();
    }
    
    // Métodos de lectura y escritura de objetos desde los archivos
    public static Equipo_Nacional consultaEquipo() throws FileNotFoundException, IOException,
    ClassNotFoundException,EOFException {
        ObjectInputStream entradaEquipo;
        entradaEquipo = new ObjectInputStream(new FileInputStream("/home/nahuel/equipos.txt"));
        Equipo_Nacional equipo1=(Equipo_Nacional)entradaEquipo.readObject();
        entradaEquipo.close();
        return equipo1;
    }
    
    public static void guardaEquipo() throws FileNotFoundException, IOException {
        try {
            ObjectOutputStream salida;
            salida = new ObjectOutputStream(new FileOutputStream("/home/nahuel/equipos.txt"));
            salida.writeObject(equipo);
            salida.close();
        } catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(null, "No se encontró el archivo");
            e.getMessage(); 
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, "Ups! Hubo un error al guardar");
            e.getMessage(); 
        }
    }
    
    public static ArrayList<Prueba> consultaPrueba() throws FileNotFoundException, IOException,
    ClassNotFoundException,EOFException {
        ObjectInputStream entradaPrueba;
        entradaPrueba = new ObjectInputStream(new FileInputStream("/home/nahuel/pruebas.txt"));
        ArrayList<Prueba> prueba1=(ArrayList<Prueba>)entradaPrueba.readObject();
        entradaPrueba.close();
        return prueba1;
    }
    
    public static void guardaPrueba() throws FileNotFoundException, IOException {
        try {
            ObjectOutputStream salidaPrueba;
            salidaPrueba = new ObjectOutputStream(new FileOutputStream("/home/nahuel/pruebas.txt"));
            salidaPrueba.writeObject(listaPruebas);
            salidaPrueba.close();
        } catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(null, "No se encontró el archivo");
            e.getMessage(); 
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, "Ups! Hubo un error al guardar");
            e.getMessage(); 
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        dialogo = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        botonIngresoAEquipo = new javax.swing.JButton();
        botonIngresoAPrueba = new javax.swing.JButton();
        botonMostrarAtletas = new javax.swing.JButton();
        botonMostrarIMC = new javax.swing.JButton();
        botonEliminarAtleta = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dialogoLayout = new javax.swing.GroupLayout(dialogo.getContentPane());
        dialogo.getContentPane().setLayout(dialogoLayout);
        dialogoLayout.setHorizontalGroup(
            dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogoLayout.setVerticalGroup(
            dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Atletas");
        setMinimumSize(new java.awt.Dimension(750, 500));

        jLabel1.setFont(new java.awt.Font("Manjari", 0, 24)); // NOI18N
        jLabel1.setText("Sistema de registro de atletas");

        botonIngresoAEquipo.setText("Ingresar un atleta para el Equipo Nacional");
        botonIngresoAEquipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIngresoAEquipo.setMaximumSize(new java.awt.Dimension(345, 25));
        botonIngresoAEquipo.setMinimumSize(new java.awt.Dimension(345, 25));
        botonIngresoAEquipo.setPreferredSize(new java.awt.Dimension(345, 25));
        botonIngresoAEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresoAEquipoActionPerformed(evt);
            }
        });

        botonIngresoAPrueba.setText("Ingresar un atleta a una prueba");
        botonIngresoAPrueba.setMaximumSize(new java.awt.Dimension(345, 25));
        botonIngresoAPrueba.setMinimumSize(new java.awt.Dimension(345, 25));
        botonIngresoAPrueba.setName(""); // NOI18N
        botonIngresoAPrueba.setPreferredSize(new java.awt.Dimension(345, 25));
        botonIngresoAPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresoAPruebaActionPerformed(evt);
            }
        });

        botonMostrarAtletas.setText("Mostrar la lista de atletas ingresados");
        botonMostrarAtletas.setMaximumSize(new java.awt.Dimension(345, 25));
        botonMostrarAtletas.setMinimumSize(new java.awt.Dimension(345, 25));
        botonMostrarAtletas.setPreferredSize(new java.awt.Dimension(345, 25));
        botonMostrarAtletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarAtletasActionPerformed(evt);
            }
        });

        botonMostrarIMC.setText("Conocer el imc y condición del peso de un atleta");
        botonMostrarIMC.setMaximumSize(new java.awt.Dimension(345, 25));
        botonMostrarIMC.setMinimumSize(new java.awt.Dimension(345, 25));
        botonMostrarIMC.setPreferredSize(new java.awt.Dimension(345, 25));
        botonMostrarIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarIMCActionPerformed(evt);
            }
        });

        botonEliminarAtleta.setText("Eliminar un atleta");
        botonEliminarAtleta.setMaximumSize(new java.awt.Dimension(345, 25));
        botonEliminarAtleta.setMinimumSize(new java.awt.Dimension(345, 25));
        botonEliminarAtleta.setPreferredSize(new java.awt.Dimension(345, 25));
        botonEliminarAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarAtletaActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.setMaximumSize(new java.awt.Dimension(72, 30));
        botonSalir.setMinimumSize(new java.awt.Dimension(72, 30));
        botonSalir.setPreferredSize(new java.awt.Dimension(72, 30));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(botonMostrarAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonMostrarIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEliminarAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonIngresoAEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonIngresoAPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(botonIngresoAEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIngresoAPrueba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMostrarAtletas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMostrarIMC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminarAtleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(142, 142, 142)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresoAEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresoAEquipoActionPerformed
        Ingreso_A_Equipo ingresoEquipo = new Ingreso_A_Equipo();
        ingresoEquipo.setVisible(true);
        ingresoEquipo.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_botonIngresoAEquipoActionPerformed

    private void botonIngresoAPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresoAPruebaActionPerformed
        Ingreso_A_Prueba ingresoPrueba = new Ingreso_A_Prueba();
        ingresoPrueba.setVisible(true);
        ingresoPrueba.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonIngresoAPruebaActionPerformed

    private void botonMostrarIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarIMCActionPerformed
        IMC imc = new IMC();
        imc.setVisible(true);
        imc.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonMostrarIMCActionPerformed

    private void botonMostrarAtletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarAtletasActionPerformed
        ListaAtletas listaAtletasIngresados = new ListaAtletas();
        listaAtletasIngresados.setVisible(true);
        listaAtletasIngresados.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonMostrarAtletasActionPerformed

    private void botonEliminarAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarAtletaActionPerformed
        Eliminar_Atleta eliminarAtleta = new Eliminar_Atleta();
        eliminarAtleta.setVisible(true);
        eliminarAtleta.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonEliminarAtletaActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que desea salir?");
        if(opcion == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, FileNotFoundException, ClassNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atletas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atletas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atletas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atletas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        try {
            equipo = consultaEquipo();
        } catch (EOFException e) {
            equipo = new Equipo_Nacional();
        }
        
        try {
            listaPruebas = consultaPrueba();
        } catch (EOFException e) {
            listaPruebas = new ArrayList<>();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Atletas_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarAtleta;
    private javax.swing.JButton botonIngresoAEquipo;
    private javax.swing.JButton botonIngresoAPrueba;
    private javax.swing.JButton botonMostrarAtletas;
    private javax.swing.JButton botonMostrarIMC;
    private javax.swing.JButton botonSalir;
    public javax.swing.JDialog dialogo;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables


}
