package sistemaatletas;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author nahuel
 */
public class IMC extends javax.swing.JFrame {

    /**
     * Creates new form IMC
     */
    public IMC() {
        initComponents();
        
        // Llena los ComboBox
        if (Atletas_GUI.equipo.getPertenece().size() >= 1){
            for(int i=0; i<Atletas_GUI.equipo.getPertenece().size(); i++){  
                listaAtletas.addItem(Atletas_GUI.equipo.getPertenece().get(i).getNombre());
            }
        }else {
            JOptionPane.showMessageDialog(null, "No hay atletas registrados");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIMCAtletas = new javax.swing.JLabel();
        labelIMC = new javax.swing.JLabel();
        labelCondicion = new javax.swing.JLabel();
        imcTextField = new javax.swing.JTextField();
        condicionTextField1 = new javax.swing.JTextField();
        botonMostrarIMC = new javax.swing.JButton();
        botonTerminar = new javax.swing.JButton();
        listaAtletas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 500));
        setMinimumSize(new java.awt.Dimension(750, 500));

        labelIMCAtletas.setFont(new java.awt.Font("Manjari", 0, 18)); // NOI18N
        labelIMCAtletas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIMCAtletas.setText("Ingrese DNI del atleta del que desea conocer condición");
        labelIMCAtletas.setMaximumSize(new java.awt.Dimension(450, 25));
        labelIMCAtletas.setMinimumSize(new java.awt.Dimension(450, 25));
        labelIMCAtletas.setPreferredSize(new java.awt.Dimension(450, 25));

        labelIMC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIMC.setText("IMC");
        labelIMC.setMaximumSize(new java.awt.Dimension(83, 30));
        labelIMC.setMinimumSize(new java.awt.Dimension(83, 30));
        labelIMC.setPreferredSize(new java.awt.Dimension(83, 30));

        labelCondicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCondicion.setText("Condición");
        labelCondicion.setMaximumSize(new java.awt.Dimension(83, 30));
        labelCondicion.setMinimumSize(new java.awt.Dimension(83, 30));
        labelCondicion.setPreferredSize(new java.awt.Dimension(83, 30));

        imcTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        imcTextField.setMaximumSize(new java.awt.Dimension(180, 30));
        imcTextField.setMinimumSize(new java.awt.Dimension(180, 30));
        imcTextField.setPreferredSize(new java.awt.Dimension(180, 30));

        condicionTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        condicionTextField1.setMaximumSize(new java.awt.Dimension(180, 30));
        condicionTextField1.setMinimumSize(new java.awt.Dimension(180, 30));
        condicionTextField1.setPreferredSize(new java.awt.Dimension(180, 30));

        botonMostrarIMC.setText("Mostrar");
        botonMostrarIMC.setMaximumSize(new java.awt.Dimension(83, 30));
        botonMostrarIMC.setMinimumSize(new java.awt.Dimension(83, 30));
        botonMostrarIMC.setPreferredSize(new java.awt.Dimension(83, 30));
        botonMostrarIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarIMCActionPerformed(evt);
            }
        });

        botonTerminar.setText("Terminar");
        botonTerminar.setMaximumSize(new java.awt.Dimension(154, 30));
        botonTerminar.setMinimumSize(new java.awt.Dimension(154, 30));
        botonTerminar.setPreferredSize(new java.awt.Dimension(154, 30));
        botonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarActionPerformed(evt);
            }
        });

        listaAtletas.setMaximumSize(new java.awt.Dimension(180, 23));
        listaAtletas.setMinimumSize(new java.awt.Dimension(180, 23));
        listaAtletas.setPreferredSize(new java.awt.Dimension(180, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelIMCAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonMostrarIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listaAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(condicionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(imcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(labelIMCAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(listaAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(botonMostrarIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(condicionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(botonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonTerminarActionPerformed

    private void botonMostrarIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarIMCActionPerformed
        //String nombreAtleta = (String)IMC.listaAtletas.getSelectedItem();
        String nombreAtleta = (String)this.listaAtletas.getSelectedItem();
        int indiceAtleta = 0;
        
        // Obtiene el índice de atleta
        for(int i=0; i<Atletas_GUI.equipo.getPertenece().size(); i++){  
            
            if (Atletas_GUI.equipo.getPertenece().get(i).getNombre().equalsIgnoreCase(nombreAtleta)){
               indiceAtleta = i;
            }
        }
        
        // Define y da formato al IMC
        float imc;
        DecimalFormat dfrmt = new DecimalFormat();
        dfrmt.setMaximumFractionDigits(2);
        
        // Muestra IMC y condición de peso
        imc = Atletas_GUI.equipo.getPertenece().get(indiceAtleta).calculaIMC();
            this.imcTextField.setText(String.valueOf(dfrmt.format(imc)));
            
        if (Atletas_GUI.equipo.getPertenece().get(indiceAtleta).hayPesoExtra(imc)){
            this.condicionTextField1.setText("Presenta sobrepeso");
        }else {
            this.condicionTextField1.setText("Peso normal");
        }
        
    }//GEN-LAST:event_botonMostrarIMCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMostrarIMC;
    public javax.swing.JButton botonTerminar;
    public javax.swing.JTextField condicionTextField1;
    public javax.swing.JTextField imcTextField;
    private javax.swing.JLabel labelCondicion;
    private javax.swing.JLabel labelIMC;
    private javax.swing.JLabel labelIMCAtletas;
    public javax.swing.JComboBox<String> listaAtletas;
    // End of variables declaration//GEN-END:variables
}
