package sistemaatletas;

import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author nahuel
 */
public class Ingreso_A_Equipo extends javax.swing.JFrame implements java.io.Serializable{
    
    /**
     * Creates new form Ingreso_A_Equipo
     */
    public Ingreso_A_Equipo() {
        initComponents();
        
        // Si hay atletas en la colección muestra cuantos hay
        if (Atletas_GUI.equipo.getPertenece().size() >= 1){
            try {
                this.atletasIngresados.setText(String.valueOf(Atletas_GUI.consultaEquipo().getPertenece().size()));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Hubo un error al leer");
                ex.getMessage();
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Tipo de objeto equivocado");
                ex.getMessage();
            }
        } else {
            this.atletasIngresados.setText("Aún no hay atletas en el equipo");
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edadAtleta = new javax.swing.JTextField();
        labelEquipo = new javax.swing.JLabel();
        alturaAtleta = new javax.swing.JTextField();
        pesoAtleta = new javax.swing.JTextField();
        botonIngresar = new javax.swing.JButton();
        botonTerminar = new javax.swing.JButton();
        nombreAtleta = new javax.swing.JTextField();
        DNIAtleta = new javax.swing.JTextField();
        atletasIngresados = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso a equipo");
        setMinimumSize(new java.awt.Dimension(750, 500));

        edadAtleta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edadAtleta.setText("Edad");
        edadAtleta.setMaximumSize(new java.awt.Dimension(180, 23));
        edadAtleta.setMinimumSize(new java.awt.Dimension(180, 23));
        edadAtleta.setPreferredSize(new java.awt.Dimension(180, 23));
        edadAtleta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edadAtletaFocusGained(evt);
            }
        });

        labelEquipo.setFont(new java.awt.Font("Manjari", 0, 18)); // NOI18N
        labelEquipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEquipo.setText("Ingrese los siguientes datos");
        labelEquipo.setPreferredSize(new java.awt.Dimension(230, 23));

        alturaAtleta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alturaAtleta.setText("Altura en metros");
        alturaAtleta.setMaximumSize(new java.awt.Dimension(180, 23));
        alturaAtleta.setMinimumSize(new java.awt.Dimension(180, 23));
        alturaAtleta.setPreferredSize(new java.awt.Dimension(180, 23));
        alturaAtleta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                alturaAtletaFocusGained(evt);
            }
        });

        pesoAtleta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pesoAtleta.setText("Peso");
        pesoAtleta.setMaximumSize(new java.awt.Dimension(180, 23));
        pesoAtleta.setMinimumSize(new java.awt.Dimension(180, 23));
        pesoAtleta.setPreferredSize(new java.awt.Dimension(180, 23));
        pesoAtleta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pesoAtletaFocusGained(evt);
            }
        });

        botonIngresar.setText("Ingresar");
        botonIngresar.setMaximumSize(new java.awt.Dimension(83, 30));
        botonIngresar.setMinimumSize(new java.awt.Dimension(83, 30));
        botonIngresar.setPreferredSize(new java.awt.Dimension(83, 30));
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        botonTerminar.setText("Terminar");
        botonTerminar.setMaximumSize(new java.awt.Dimension(154, 30));
        botonTerminar.setMinimumSize(new java.awt.Dimension(154, 30));
        botonTerminar.setPreferredSize(new java.awt.Dimension(154, 30));
        botonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarActionPerformed(evt);
            }
        });

        nombreAtleta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreAtleta.setText("Nombre");
        nombreAtleta.setMaximumSize(new java.awt.Dimension(180, 23));
        nombreAtleta.setMinimumSize(new java.awt.Dimension(180, 23));
        nombreAtleta.setPreferredSize(new java.awt.Dimension(180, 23));
        nombreAtleta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreAtletaFocusGained(evt);
            }
        });

        DNIAtleta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DNIAtleta.setText("DNI");
        DNIAtleta.setMaximumSize(new java.awt.Dimension(180, 23));
        DNIAtleta.setMinimumSize(new java.awt.Dimension(180, 23));
        DNIAtleta.setPreferredSize(new java.awt.Dimension(180, 23));
        DNIAtleta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DNIAtletaFocusGained(evt);
            }
        });

        atletasIngresados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        atletasIngresados.setMaximumSize(new java.awt.Dimension(250, 25));
        atletasIngresados.setMinimumSize(new java.awt.Dimension(250, 25));
        atletasIngresados.setName(""); // NOI18N
        atletasIngresados.setPreferredSize(new java.awt.Dimension(250, 25));

        jLabel1.setText("Cantidad de atletas registrados");
        jLabel1.setMaximumSize(new java.awt.Dimension(205, 23));
        jLabel1.setMinimumSize(new java.awt.Dimension(205, 23));
        jLabel1.setPreferredSize(new java.awt.Dimension(205, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 571, Short.MAX_VALUE)
                .addComponent(botonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(DNIAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edadAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alturaAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesoAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atletasIngresados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(labelEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNIAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(edadAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alturaAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesoAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(atletasIngresados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(botonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed

        // Toma los valores que ingresa el usuario
        String nombre;
        int dni;
        int edad;
        float altura;
        int peso;
        try {
            nombre = this.nombreAtleta.getText();
            dni = Integer.parseInt(this.DNIAtleta.getText());
            edad = Integer.parseInt(this.edadAtleta.getText());
            altura = Float.parseFloat(this.alturaAtleta.getText());
            peso = Integer.parseInt(this.pesoAtleta.getText());
            
            // Crea y agrega atletas a la colección
            Atletas_GUI.equipo.setPertenece(new Atleta(nombre, dni, edad, altura, peso));
            JOptionPane.showMessageDialog(null, "Atleta guardado");
            
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Los datos ingresados no son correctos");
        }
        
        // Muestra la cantidad de atletas registrados
        this.atletasIngresados.setText(String.valueOf(Atletas_GUI.equipo.getPertenece().size()));
        
        // Guarda las modificaciones
        try { 
            Atletas_GUI.guardaEquipo();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Ups! Algo salió mal");
            ex.getMessage();
        }
        
        // Vuelve a colocar placeholders
        this.nombreAtleta.setText("Nombre");
        this.DNIAtleta.setText("DNI");
        this.edadAtleta.setText("Edad");
        this.alturaAtleta.setText("Altura");
        this.pesoAtleta.setText("Peso");
        
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void botonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonTerminarActionPerformed

    private void nombreAtletaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreAtletaFocusGained
        this.nombreAtleta.setText("");
    }//GEN-LAST:event_nombreAtletaFocusGained

    private void DNIAtletaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DNIAtletaFocusGained
        this.DNIAtleta.setText("");
    }//GEN-LAST:event_DNIAtletaFocusGained

    private void edadAtletaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edadAtletaFocusGained
        this.edadAtleta.setText("");
    }//GEN-LAST:event_edadAtletaFocusGained

    private void alturaAtletaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alturaAtletaFocusGained
        this.alturaAtleta.setText("");
    }//GEN-LAST:event_alturaAtletaFocusGained

    private void pesoAtletaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesoAtletaFocusGained
        this.pesoAtleta.setText("");
    }//GEN-LAST:event_pesoAtletaFocusGained

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso_A_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso_A_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso_A_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso_A_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso_A_Equipo().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField DNIAtleta;
    public javax.swing.JTextField alturaAtleta;
    public javax.swing.JTextField atletasIngresados;
    public javax.swing.JButton botonIngresar;
    public javax.swing.JButton botonTerminar;
    public javax.swing.JTextField edadAtleta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelEquipo;
    public javax.swing.JTextField nombreAtleta;
    public javax.swing.JTextField pesoAtleta;
    // End of variables declaration//GEN-END:variables
}
